### ISSUE TITLE
AttributeError: 'SelfDebiasingGPT2LMHeadModel' object has no attribute '_init_sequence_length_for_generation'

### ISSUE THREAD

**Issue by HaoBytes** [timoschick/dino#16]
Done loading 6 inputs from file 'sts-x1-dataset.jsonl'
Starting dataset generation with DINO...
Dataset Entries:   0%|                                                                       | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/lihao/pythonProject/pythonProject/dino.py", line 161, in <module>
    outputs = generator.generate_dataset(inputs, num_entries_per_input_and_label=args.num_entries_per_input_and_label,
  File "/Users/lihao/pythonProject/pythonProject/modeling.py", line 98, in generate_dataset
    dataset += self._generate_dataset_entries(input_text_or_id, label=label, num_entries=num_entries_per_input_and_label,
  File "/Users/lihao/pythonProject/pythonProject/modeling.py", line 125, in _generate_dataset_entries
    model_outputs = self.model.generate_self_debiasing(
  File "/Users/lihao/pythonProject/pythonProject/modeling.py", line 280, in generate_self_debiasing
    output_ids = self._model.generate(**inputs, min_length=min_length, max_length=max_length, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/generation_utils.py", line 1310, in generate
    return self.sample(
  File "/Users/lihao/pythonProject/pythonProject/generation.py", line 170, in sample
    sequence_lengths, unfinished_sequences, cur_len = self._init_sequence_length_for_generation(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SelfDebiasingGPT2LMHeadModel' object has no attribute '_init_sequence_length_for_generation'
-------------------------------------------------------------------------------------------------------------------------
Hi, when I running the model, I meeting this problem. any idea to solve it? thanks!

**Comment by HaoBytes** [comment]
solved
